---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(knitr)
library(httr)
library(readxl)
# library(xlsx)
library(lubridate)
library(forecast)
library(feasts)
library(tsibble)
library(kableExtra)
library(openxlsx)
```

https://www.arcgis.com/sharing/rest/content/items/f218592c7fe74788906cc6a0eb190af9/data

```{r message=FALSE, warning=FALSE}
url <- "https://www.arcgis.com/sharing/rest/content/items/f218592c7fe74788906cc6a0eb190af9/data"
GET(url, write_disk(path <- tempfile(fileext = ".xlsx")))
```


```{r message=FALSE, warning=FALSE}
# readxl way - for certain sheets with issues
bikes <- path %>%
   excel_sheets() %>%          # parses xlsx file
   set_names() %>%             # get tibble row names from sheet names
   map(read_excel, path = path)  # map sheet data into tibble

# read xlsx way - for other excel issues like leapyears
read_all_sheets = function(xlsxFile, ...) {
  sheet_names = openxlsx::getSheetNames(xlsxFile)
  sheet_list = sapply(sheet_names, function(sn){openxlsx::read.xlsx(xlsxFile, sheet=sn, ...)}, USE.NAMES = TRUE)
 return(sheet_list)
}
bikes2 <- read_all_sheets(path, detectDates = TRUE)
```


```{r message=FALSE, warning=FALSE}
#2019 - observations end in Sept; 
#  contains footer that confuses xlsx reader 

df19 <- bikes[['2019']] %>%
  slice_head(n = 273) %>%
  mutate(Date = as_date(as.numeric(Date), origin = ymd('1899-12-30'))) %>%
  # often missing values need to be coerced from char to num
  mutate_if(is.character,as.numeric)
names(df19) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET",
                 "OGLD", "OBVW", "ADAWE.1", "ADAWE.2")
# 2018
df18 <- bikes2[["2018"]]
names(df18) <- c("Date", "ALEX", "ORPY", "COBY", "LMET", "SOMO",
                 "OGLD", "OBVW", "ADAWE.1", "ADAWE.2")
# 2017
df17 <- bikes[['2017']] %>%
  mutate(Date = as_date(Date, format = "%d/%m/%Y"))
names(df17) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET",
                 "SOMO", "OGLD", "OBVW", "ADAWE.1", "ADAWE.2")

# 2016 ~ a leap year (huge problem with Excel in general)
df16 <- bikes[['2016']] 
names(df16) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET", "LLYN", "SOMO",
                 "OYNG", "OGLD", "OBVW", "ADAWE.1", "ADAWE.2")
df16.top <- df16 %>%
  slice_head(n = 91) %>%
  mutate(Date = as_date(as.numeric(Date), origin = ymd('1899-12-30')))
df16 <-  df16 %>%
  slice_tail(n = 366 - 91) %>%
    mutate(Date = as_date(dmy(str_replace_all(Date, '/', '-')))) %>%
  # # concatenate halves
  bind_rows(df16.top, .) %>%
  mutate_if(is.character,as.numeric)
rm(df16.top)

# 2015
df15 <- bikes2[["2015"]]
names(df15) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET",
                 "LLYN", "SOMO", "OYNG", "OGLD", "OBVW", "Portage")
# 2014
df14 <- bikes2[["2014"]] %>%
  mutate_if(is.character, as.numeric)
names(df14) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET",
                 "LLYN", "SOMO", "OYNG", "OGLD", "OBVW", "Portage")

# 2013 - coerce to num, remove empty bottom row
df13 <- bikes[["2013"]] %>%
  slice_head(n=365) %>%
  mutate(Date = as_date(as.numeric(Date), origin = ymd('1899-12-30'))) %>%
  mutate_if(is.character,as.numeric)
names(df13) <- c("Date", "ALEX", "ORPY", "COBY", "CRTZ", "LMET", "LLYN",
                 "LBAY", "SOMO", "OYNG", "OGLD", "OBVW", "Portage")


# 2012 ~ a leap year (huge problem with Excel in general)
df12 <- bikes[['2012']] 
names(df12) <- c("Date", "ALEX", "CRTZ", "COBY", "ORPY","SOMO",
                 "LBAY","LLYN", "LMET")
df12.top <- df12 %>%
  slice(2:91) %>%
  mutate(Date = as_date(dmy(substr(Date, 5, nchar(Date)))))
df12 <-  df12 %>%
  slice_tail(n = 366 - 91) %>%
  mutate(Date = as_date(as.numeric(Date), origin = ymd('1899-12-30'))) %>%
  # # concatenate halves
  bind_rows(df12.top, .) %>%
  mutate_if(is.character,as.numeric)
rm(df12.top)

# 2011
df11 <- bikes2[["2011"]]  %>%
  select(c(1:5)) %>%
  slice_tail(n = 366-1) %>%
  mutate(Date = as_date(dmy(substr(Date, 5, nchar(Date))))) %>%
  mutate_if(is.character,as.numeric)
names(df11) <- c("Date", "ALEX", "CRTZ", "COBY", "ORPY")

# 2010
df10 <- bikes2[["2010"]] %>%
  slice_tail(n = 366-1) %>%
  mutate(Date = as_date(dmy(substr(Date, 5, nchar(Date))))) %>%
  mutate_if(is.character,as.numeric)
names(df10) <- c("Date", "ALEX", "COBY", "ORPY")

###
```


```{r message=FALSE, warning=FALSE}
# Concatenate all sheets into single tidy dataframe
bikes.ts <- bind_rows(df10, df11, df12, df13, df14, df15,
                      df16, df17, df18, df19) %>%
  select(-c(15))

names(bikes.ts) <- c("Date","Alexandra", "Colonel By", "Ottawa River", 
                     "Canal Ritz", "Somerset", "Laurier/Bay", "Laurier/Lyon",
                     "Laurier/Metcalfe", "OTrain/Young", "OTrain/Gladstone",
                     "OTrain/Bayview", "Portage","Adawé")

  
bikes.ts <- bikes.ts %>%
  pivot_longer(c(2:14), names_to = 'location', values_to = 'count') %>%
  as_tsibble(key = 'location', index = 'Date')

rm(list = c("df10", "df11", "df12", "df13", "df14", "df15",
            "df16", "df17", "df18", "df19", "bikes2", "bikes.df"))

summary(bikes.ts)
saveRDS(bikes.ts, "data/ottbike_counters.ts.RDS")
write.csv(bikes.ts, "data/ottbike_counters.ts.csv")

```
```{r}
rm(list = ls())
```

